feat: CD jobs for linux and windows

diff --git a/.github/workflows/linux.yaml b/.github/workflows/linux.yaml
--- a/.github/workflows/linux.yaml
+++ b/.github/workflows/linux.yaml
@@ -19,3 +19,18 @@ jobs:
       run: |
         chmod +x build.sh
         ./build.sh
+
+    - name: Run Tests
+      run: |
+        ./build/client/babel_client 2> stderr.log
+        
+        if [ $? -ne 0 ];
+          then echo "Binary crashed";
+          exit 1;
+        fi
+        
+        if [ -s stderr.log ]; then
+          echo "Errors detected in stderr:"
+          cat stderr.log
+          exit 1
+        fi
diff --git a/.github/workflows/windows.yaml b/.github/workflows/windows.yaml
--- a/.github/workflows/windows.yaml
+++ b/.github/workflows/windows.yaml
@@ -13,3 +13,17 @@ jobs:
 
     - name: Run Build Script
       run: .\build.bat
+    
+    - name: Run Smoke Test
+      shell: pwsh
+      run: |
+        $stderrFile = "stderr.txt"
+        Start-Process -FilePath ".\build\client\Release\babel_client.exe" -NoNewWindow -Wait -RedirectStandardError $stderrFile
+        
+        if (Test-Path $stderrFile) {
+            $errContent = Get-Content $stderrFile
+            if ($errContent) {
+                Write-Error "Errors found in std::cerr: $errContent"
+                exit 1
+            }
+        }
