feat: upload test

diff --git a/.github/workflows/windows.yaml b/.github/workflows/windows.yaml
--- a/.github/workflows/windows.yaml
+++ b/.github/workflows/windows.yaml
@@ -14,7 +14,7 @@ jobs:
     - name: Run Build Script
       run: .\build.bat
     
-    - name: Run Smoke Test
+    - name: Run Exec Tests
       shell: pwsh
       run: |
         New-Item -Path . -Name "stderr.txt" -ItemType "file" -Force
@@ -35,3 +35,8 @@ jobs:
             exit 1
         }
 
+        $errContent = Get-Content $stderrPath
+        if ($errContent) {
+            Write-Error "Errors detected in std::cerr: $errContent"
+            exit 1
+        }
